backend:
  # name: test-repo
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img

collections:
  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and last or nickname"
              - label: "Introduction"
                name: "introduction"
                widget: "text"

      - name: "languages"
        label: "Languages"
        file: "meta/languages.yml"
        description: "Post languages"
        fields:
          - name: languages
            label: Languages
            label_singular: "Language"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the language"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Language name for displaying on the site"


      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false

      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"

      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields: ["tags.*.name"]
          displayFields: ["tags.*.name"]
          valueField: "tags.*.slug"

      - label: Languages
        name: "languages"
        widget: relation
        collection: "meta"
        file: "languages"
        searchFields:
          - "languages.*.name"
        displayFields:
          - "languages.*.name"
        valueField: "languages.*.slug"

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        
      - label: "Body"
        name: "body"
        widget: "markdown"
   